pip3 install --no-dependencies /tmp/packages/traitlets-5.9.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/platformdirs-3.1.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pyrsistent-0.19.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pkgutil_resolve_name-1.3.10-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/attrs-22.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_core-5.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jsonschema-4.17.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/fastjsonschema-2.16.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/pyzmq-25.0.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
pip3 install --no-dependencies /tmp/packages/importlib_metadata-6.0.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pycparser-2.21-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/webencodings-0.5.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbformat-5.7.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_client-8.0.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/soupsieve-2.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ptyprocess-0.7.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/cffi-1.15.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/tinycss2-1.2.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Pygments-2.14.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pandocfilters-1.5.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbclient-0.7.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/mistune-2.0.5-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_pygments-0.2.2-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Jinja2-3.1.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/defusedxml-0.7.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/bleach-6.0.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/beautifulsoup4-4.11.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/terminado-0.17.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/rfc3986_validator-0.1.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/rfc3339_validator-0.1.4-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
pip3 install --no-dependencies /tmp/packages/python_json_logger-2.0.7-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/sniffio-1.3.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/idna-3.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pure_eval-0.2.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/executing-1.2.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/asttokens-2.2.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/wcwidth-0.2.6-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/parso-0.8.3-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/websocket_client-1.5.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Send2Trash-1.8.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/prometheus_client-0.16.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbconvert-7.2.9-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_server_terminals-0.4.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_events-0.6.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/argon2_cffi-21.3.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/anyio-3.6.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/stack_data-0.6.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/prompt_toolkit-3.0.38-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pickleshare-0.7.5-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pexpect-4.8.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/matplotlib_inline-0.1.6-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jedi-0.18.2-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/decorator-5.1.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/backcall-0.2.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_server-2.4.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/nest_asyncio-1.5.6-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipython-8.11.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/debugpy-1.6.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/comm-0.1.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/notebook_shim-0.2.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipython_genutils-0.2.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipykernel-6.21.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/urllib3-1.26.15-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/certifi-2022.12.7-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/y_py-0.5.9-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/aiosqlite-0.18.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/aiofiles-22.1.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbclassic-0.5.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/requests-2.28.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/json5-0.9.11-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Babel-2.12.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ypy_websocket-0.8.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_ydoc-0.2.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_server_fileid-0.8.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/tomli-2.0.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/notebook-6.5.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_server-2.20.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_server_ydoc-0.6.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/QtPy-2.3.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/widgetsnbextension-4.0.5-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_widgets-3.0.5-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab-3.6.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/qtconsole-5.4.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_console-6.6.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipywidgets-8.0.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/lckr_jupyterlab_variableinspector-3.0.9.tar.gz
pip3 install --no-dependencies /tmp/packages/jupyter-1.0.0-py2.py3-none-any.whl
